#!/usr/bin/env bash

touch /etc/apt/sources.list.d/resilio-sync.list
echo "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free" | sudo tee /etc/apt/sources.list.d/resilio-sync.list
curl -L https://linux-packages.resilio.com/resilio-sync/key.asc | sudo apt-key add
echo "added resilioSync GPG key to Keyring"
sudo apt update && sudo apt install resilio-sync
echo "Resilio has now been installed"
