#!/usr/bin/env bash

ZSH_CONFIG_FILE="~/.zshrc"

if [[ -f $ZSH_CONFIG_FILE ]]; then
	echo 'notica() { curl --data "d:$*" "https://notica.us/?nFpv-M" ; }' >> ~/.zshrc && source ~/.zshrc	
else
	echo 'notica() { curl --data "d:$*" "https://notica.us/?nFpv-M" ; }' >> ~/.bashrc && source ~/.bashrc
fi

echo "Notica has now been installed"
