#!/usr/bin/env bash
[[ $EUID -ne 0 ]] && echo "This script must be run as root." && exit 1

DEP1="curl"
DEP2="apt-transport-https"
DEP3="ca-certificates"
DEP4="gnupg"
DEP5="lsb-release"

dpkg -s DEV1 &> /dev/null

if [ $DEV1 -eq 0 ]; then
	echo "Dependency Curl is installed"
else
	apt install curl
fi

dpkg -s DEV2 &> /dev/null

if [ $DEV2 -eq 0 ]; then
	echo "Dependency apt-transport-https is installed"
else
	apt install apt-transport-https
fi

dpkg -s DEV3 &> /dev/null

if [ $DEV3 -eq 0 ]; then
	echo "Dependency ca-certificates is installed"
else
	apt install ca-certificates
fi

dpkg -s DEV4 &> /dev/null

if [ $DEV4 -eq 0 ]; then
	echo "Dependency gnupg is installed"
else
	apt install gnupg
fi

dpkg -s DEV5 &> /dev/null

if [ $DEV5 -eq 0 ]; then
	echo "Dependency lsb-release is installed"
else
	apt install lsb-release
fi

echo "dependecies installed"

echo "retrieving docker repo key"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "docker repo unlocked"

echo "adding docker repo to list"
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt update && apt install docker-ce docker-ce-cli containerd.io

groupadd docker && usermod -aG docker $USER && newgrp docker

echo "docker now installed"
